USE INVENTORY;


-------------------------------------------------ASSIGNMENT-8------------------------------------------------------------------------
-- 1) ADDSUPPLIER – THIS PROCEDURE SHOULD ADD THE SUPPLIER IN THE SUPLIER TABLE AND DISPLAY THE DETAILS OF THE NEW SUPPLIER ADDED.

--BELOW CODE TAKEN HERE FOR REFERENCE
--CREATE TABLE SUPPLIER(
--SID CHAR(5),
--SNAME VARCHAR(50) NOT NULL,
--SADD VARCHAR(75) NOT NULL,
--SCITY VARCHAR(20),
--SPHONE CHAR(10),
--EMAIL VARCHAR(40),
--PRIMARY KEY(SID)

DROP PROCEDURE ADDSUPPLIER;
CREATE PROCEDURE ADDSUPPLIER @SID AS CHAR(5),@SNAME AS VARCHAR(50), @SADD AS VARCHAR(75), @SCITY AS VARCHAR(20), @SPHONE AS CHAR(10), @EMAIL AS VARCHAR(40)
AS 
BEGIN
	INSERT INTO SUPPLIER
	VALUES (@SID, @SNAME, @SADD, @SCITY, @SPHONE, @EMAIL);
	SELECT * FROM SUPPLIER WHERE SID=@SID;
END;

DELETE FROM SUPPLIER WHERE SID='S0011';
ADDSUPPLIER 'S0011','PFIZER LTD','CHEMICAL INDUSTRIES AREA, BANGALORE','BANGALORE', '8456135875', 'PFIZER.INFO@GMAIL.COM';


-- 2) ADDPRO – THIS PROCEDURE SHOULD ADD THE PRODUCT IN THE PRODUCT TABLE AND DISPLAY THE DETAILS OF THE NEW PRODUCT ADDED.

--BELOW CODE TAKEN HERE FOR REFERENCE
--CREATE TABLE PRODUCT(
--PID CHAR(5),
--PDESC VARCHAR(50) NOT NULL,
--PRICE FLOAT CHECK(PRICE>0),
--CATEGORY VARCHAR(5)  CHECK (CATEGORY IN ('IT','HA','HC')),
--SID CHAR(5),
--PRIMARY KEY (PID)
--);


CREATE PROCEDURE ADDPRO @PID AS CHAR(5), @PDESC AS VARCHAR(50), @PRICE AS FLOAT, @CATEGORY AS VARCHAR(5), @SID AS CHAR(5)
AS
BEGIN
	INSERT INTO PRODUCT 
	VALUES (@PID,@PDESC,@PRICE,@CATEGORY,@SID);
	SELECT * FROM PRODUCT WHERE PID=@PID;
END;

ADDPRO 'P0016','COVID VACCINE',5000,'HC','S0011';

-- 3) ADDCUST – THIS PROCEDURE SHOULD ADD THE CUSTOMER IN THE CUSTOMER TABLE AND DISPLAY THE DETAILS OF THE NEW CUSTOMER ADDED.

--BELOW CODE TAKEN HERE FOR REFERENCE
--CREATE TABLE CUST(
--CID CHAR(5),
--CNAME VARCHAR(50) NOT NULL,
--ADDRESS VARCHAR(75) NOT NULL,
--CITY VARCHAR(20) NOT NULL,
--PHONE CHAR(10) NOT NULL,
--EMAIL VARCHAR(40) NOT NULL,
--DOB DATE,
--PRIMARY KEY(CID)
--);

CREATE PROCEDURE ADDCUST @CID AS CHAR(5), @CNAME AS VARCHAR(50), @ADDRESS AS VARCHAR(75), @CITY AS VARCHAR(20), @PHONE AS CHAR(10), @EMAIL AS VARCHAR(40), @DOB AS DATE
AS 
BEGIN
	INSERT INTO CUST 
	VALUES (@CID,@CNAME,@ADDRESS,@CITY,@PHONE,@EMAIL,@DOB);
	SELECT * FROM CUST WHERE CID=@CID;
END;

ADDCUST 'C0011','ANTHONY GONJALVIS','TECH CITY AREA','BANGALORE','8564135795','ANTHGONJA@GMAIL.COM','12-SEP-1990';


-- 4) ADDORDER – THIS PROCEDURE SHOULD ADD THE ORDER IN THE ORDERS TABLE AND DISPLAY THE DETAILS OF THE ORDER. 
-- ORDER DATE SHOULD BE CURRENT DATE AND SHOULD COME AUTOMATICALLY.

--BELOW CODE TAKEN HERE FOR REFERENCE
--CREATE TABLE ORDERS(
--OID CHAR(5),
--ODATE DATE,
--CID CHAR(5) REFERENCES CUST(CID),
--PID CHAR(5) REFERENCES PRODUCT(PID),
--OQTY INT CHECK(OQTY>=1),
--PRIMARY KEY(OID)
--);


CREATE PROCEDURE ADDORDER @OID AS CHAR(5), @CID AS CHAR(5), @PID AS CHAR(5), @OQTY INT
AS 
BEGIN
	INSERT INTO ORDERS 
	VALUES (@OID,CONVERT(DATE,GETDATE()),@CID,@PID,@OQTY);
	SELECT * FROM ORDERS WHERE OID=@OID;
END;

-- BELOW ARE TWO OPTIONS TO GET ONLY DATE FROM GETDATE FUNCTION
SELECT CAST(GETDATE() AS DATE);
SELECT CONVERT(DATE,GETDATE());

ADDORDER 'O0006','C0011','P0016',2;


------------------------------------------------------ASSIGNMENT-9-----------------------------------------------------------
--IN THIS ASSIGNMENT WE WILL RE-CREATE ALL ABOVE PROCEDURES WITH BELOW INSTRUCTIONS 

--A-1 : CREATE A FUNCTION FOR AUTOGENERATION OF 5 CHARACTERS ALPHA NUMERIC ID. IT SHOULD ACCEPT 2 PARAMETERS A CHARACTER AND THE NUMBER AND 
--RETURN THE ID BY CONCANATING THE CHARACTER , REQUIRED ZEROS AND THE SPECIFIED NUMBER. 
--RECREATE BELOW PROCEDURES IN THE INVENTORY DATABASE AS SPECIFIED (ALL THE ID s SHOULD BE AUTOMATICALLY GENERATED USING ABOVE CREATED FUNCTION AND SEQUENCES) :

--LETS FIRST DROP ALL EXISTING PROCEDURE AND WE WILL RE-CREATE THEM.
DROP PROCEDURE ADDSUPPLIER;
DROP PROCEDURE ADDPRO;
DROP PROCEDURE ADDCUST;
DROP PROCEDURE ADDORDER;

--LETS CREATE THE SEQUENCE AND THEN FUNCTIN FOR AUTOMATIC GERATION OF ID'S
DROP SEQUENCE SEQSUPP;
CREATE SEQUENCE	SEQSUPP 
AS INT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE	SEQPRO 
AS INT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE	SEQCUST 
AS INT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE	SEQORDER
AS INT
START WITH 1
INCREMENT BY 1;

-- NOW WE WILL GENERATE A FUNCTION TO GENERATE ALPHA NUMERIC ID'S

DROP FUNCTION GENID;

CREATE FUNCTION GENID (@CH AS CHAR(1),@I AS INT)
RETURNS CHAR(5)
AS 
BEGIN
	DECLARE @R AS CHAR(5);

	SET @R=CASE
				WHEN @I<10 THEN CONCAT(@CH,'000',@I)
				WHEN @I<100 THEN CONCAT(@CH,'00',@I)
				WHEN @I<1000 THEN CONCAT(@CH,'0',@I)
				WHEN @I<10000 THEN CONCAT(@CH,@I)
				ELSE NULL
			END;
	RETURN @R;
END;

-- NEW ADDSUPPLIER PROCEDURE
DROP PROCEDURE ADDSUPPLIER;
CREATE PROCEDURE ADDSUPPLIER @SNAME AS VARCHAR(50), @SADD AS VARCHAR(75), @SCITY AS VARCHAR(20), @SPHONE AS CHAR(10), @EMAIL AS VARCHAR(40)
AS 
BEGIN
	DECLARE @I AS INT,@SID AS CHAR(5);
	
	SET @I= NEXT VALUE FOR SEQSUPP;
	SET @SID = DBO.GENID('S',@I)

	INSERT INTO SUPPLIER
	VALUES (@SID, @SNAME, @SADD, @SCITY, @SPHONE, @EMAIL);
	SELECT * FROM SUPPLIER WHERE SID=@SID;
END;

--DELETE FROM SUPPLIER WHERE SID='S01';
ADDSUPPLIER 'DATA CARE CORPORATION','SECTOR 12','GURGAON', '8756135875', 'DCC.SAKES@GMAIL.COM';


CREATE PROCEDURE ADDPRO @PDESC AS VARCHAR(50), @PRICE AS FLOAT, @CATEGORY AS VARCHAR(5), @SID AS CHAR(5)
AS
BEGIN
	DECLARE @I AS INT,@PID AS CHAR(5);
	
	SET @I= NEXT VALUE FOR SEQPRO;
	SET @PID = DBO.GENID('P',@I)

	INSERT INTO PRODUCT 
	VALUES (@PID,@PDESC,@PRICE,@CATEGORY,@SID);
	SELECT * FROM PRODUCT WHERE PID=@PID;
END;

ADDPRO 'DELL INSPIRON LAPTOP',50000,'IT','S0012';


CREATE PROCEDURE ADDCUST @CNAME AS VARCHAR(50), @ADDRESS AS VARCHAR(75), @CITY AS VARCHAR(20), @PHONE AS CHAR(10), @EMAIL AS VARCHAR(40), @DOB AS DATE
AS 
BEGIN
	DECLARE @I AS INT,@CID AS CHAR(5);
	
	SET @I= NEXT VALUE FOR SEQCUST;
	SET @CID = DBO.GENID('C',@I)

	INSERT INTO CUST 
	VALUES (@CID,@CNAME,@ADDRESS,@CITY,@PHONE,@EMAIL,@DOB);
	SELECT * FROM CUST WHERE CID=@CID;
END;

ADDCUST 'SAHIL FERNANDES','MAGARPATTA CITY','PUNE','8564842795','SAHFER@GMAIL.COM','28-OCT-1994';


CREATE PROCEDURE ADDORDER @CID AS CHAR(5), @PID AS CHAR(5), @OQTY INT
AS 
BEGIN
	DECLARE @I AS INT,@OID AS CHAR(5);
	
	SET @I= NEXT VALUE FOR SEQORDER;
	SET @OID = DBO.GENID('O',@I)

	INSERT INTO ORDERS 
	VALUES (@OID,CONVERT(DATE,GETDATE()),@CID,@PID,@OQTY);
	SELECT * FROM ORDERS WHERE OID=@OID;
END;

ADDORDER 'C0012','P0017',1;