USE DEMO;

DROP PROCEDURE PRINTING;

CREATE PROCEDURE PRINTING @R AS INT
AS 
BEGIN
	DECLARE @C1 AS INT,@C2 AS INT,@FINAL AS VARCHAR(100);
	SET @C1=1;
	WHILE @C1 <=@R
	BEGIN 
		SET @C2=1;
		SET @FINAL=NULL;
		WHILE @C2 <=@C1
		BEGIN
			SET @FINAL = ISNULL(@FINAL,'')+'*'+' ';
			SET @C2=@C2+1;
		END;
		PRINT @FINAL
		SET @C1=@C1+1;
	END;   
END;

PRINTING 10;