USE DEMO;

DROP TABLE TEST;
CREATE TABLE TEST
(RNO INT,
NAME CHAR(10));

INSERT INTO TEST VALUES (1,'A');
INSERT INTO TEST VALUES (2,'B');
INSERT INTO TEST VALUES (3,'C');
INSERT INTO TEST VALUES (4,'D');
INSERT INTO TEST VALUES (5,'E');
INSERT INTO TEST VALUES (6,'F');
INSERT INTO TEST VALUES (7,'G');
INSERT INTO TEST VALUES (8,'H');
INSERT INTO TEST VALUES (9,'I');
INSERT INTO TEST VALUES (10,'J');


SELECT * FROM TEST;


DELETE FROM TEST WHERE RNO = 10;

ROLLBACK;

BEGIN TRANSACTION;

DELETE FROM TEST WHERE RNO = 9;
DELETE FROM TEST WHERE RNO = 8;
DELETE FROM TEST WHERE RNO = 7;
DELETE FROM TEST WHERE RNO = 6;



BEGIN TRANSACTION;

DELETE FROM TEST WHERE RNO = 9;
DELETE FROM TEST WHERE RNO = 8;

COMMIT;
ROLLBACK;
SELECT * FROM TEST;


BEGIN TRANSACTION;

DELETE FROM TEST WHERE RNO = 5;
DELETE FROM TEST WHERE RNO = 6;

SAVE TRANSACTION T1; -- SAVE POINTS
DELETE FROM TEST WHERE RNO = 7;

SAVE TRANSACTION T2;
DELETE FROM TEST WHERE RNO = 8;

SAVE TRANSACTION T3;
DELETE FROM TEST WHERE RNO = 9;

SAVE TRANSACTION T4;
DELETE FROM TEST WHERE RNO = 10;

SELECT * FROM TEST;
ROLLBACK TRANSACTION T1;
SELECT * FROM TEST;

DROP TABLE EMP2;
CREATE TABLE EMP2
(ID INT IDENTITY (1,1),-- START , INCREMENT
NAME VARCHAR(10),
AGE INT);


INSERT INTO EMP2 (NAME, AGE)
VALUES ('AJAY', 24);

INSERT INTO EMP2 (NAME, AGE)
VALUES ('MOHIT', 24);

INSERT INTO EMP2 
VALUES ('KAPIL', 25);

INSERT INTO EMP2 
VALUES ('SUBASH', 26);

INSERT INTO EMP2
VALUES('MANPREET', 23);
SELECT * FROM EMP2;

DELETE FROM EMP2 WHERE ID = 4;
DROP PROCEDURE ADDEMP2 ;
CREATE PROCEDURE ADDEMP2 @N AS VARCHAR(10), @X AS INT
AS
BEGIN
		INSERT INTO EMP2
		VALUES(@N, @X);
		SELECT * FROM EMP2;

END;

ADDEMP2 'RAMESH', 24
ADDEMP2 'ABHISHEK', 26


DROP SEQUENCE MYSEQ ;
CREATE SEQUENCE MYSEQ 
AS INT
START WITH 1
INCREMENT BY 1
MAXVALUE 10
MINVALUE 1
CYCLE
CACHE 5;

SELECT NEXT VALUE FOR MYSEQ;
DROP SEQUENCE SEQEMP;

CREATE SEQUENCE SEQEMP 
AS INT
START WITH 1
INCREMENT BY 1;

CREATE TABLE EMP2
(ID INT ,
NAME VARCHAR(10),
AGE INT);

INSERT INTO EMP2
VALUES(NEXT VALUE FOR SEQEMP, 'AJAY', 26);

INSERT INTO EMP2
VALUES(NEXT VALUE FOR SEQEMP, 'KAPIL', 26);


SELECT * FROM EMP2;

CREATE PROCEDURE ADDEMP2 @N AS VARCHAR(10), @X AS INT
AS
BEGIN
		INSERT INTO EMP2
		VALUES(NEXT VALUE FOR SEQEMP, @N, @X);
		
		SELECT * FROM EMP2;

END;

ADDEMP2 'ROHAN' , 27;
ADDEMP2 'ABHIJEET' , 28;
ADDEMP2 'NEETU' , 25;

SELECT NEXT VALUE FOR SEQEMP;

DROP TABLE EMP2
CREATE TABLE EMP2
(ID CHAR(5),
NAME VARCHAR(10),
AGE INT);

DROP PROCEDURE ADDEMP2;
CREATE PROCEDURE ADDEMP2 @N AS VARCHAR(10), @X AS INT
AS
BEGIN
		DECLARE @I AS INT;
		DECLARE @ID AS CHAR(5);

		SET @I = (NEXT VALUE FOR SEQEMP);
		IF @I <10
			SET @ID =CONCAT('E000', @I);
		ELSE IF @I <100
			SET @ID =CONCAT('E00', @I);
		ELSE IF @I <1000
			SET @ID =CONCAT('E0', @I);
		ELSE IF @I <10000
			SET @ID =CONCAT('E', @I);


		INSERT INTO EMP2
		VALUES(@ID, @N, @X);
		
		SELECT * FROM EMP2;

END;


ADDEMP2 'MOHIT', 24;
ADDEMP2 'RAJAT', 24;
ADDEMP2 'ABHI', 26;
ADDEMP2 'DEEPAK', 27;


DROP FUNCTION GENID;
CREATE FUNCTION GENID (@CH AS CHAR(1), @I AS INT)
RETURNS CHAR(5)
AS
BEGIN
		DECLARE @R AS CHAR(5);

		SET @R = CASE										-- HERE SET OR SELECT BOTH WORKS
					WHEN @I < 10 THEN CONCAT (@CH,'000',@I)
					WHEN @I < 100 THEN CONCAT (@CH,'00',@I)
					WHEN @I < 1000 THEN CONCAT (@CH,'0',@I)
					WHEN @I < 10000 THEN CONCAT (@CH,@I)
					ELSE NULL	
					END;
		RETURN @R;
END;

SELECT DBO.GENID('P', 4);

DROP PROCEDURE ADDEMP2;
CREATE PROCEDURE ADDEMP2 @N AS VARCHAR(10), @X AS INT
AS
BEGIN
		DECLARE @I AS INT;
		DECLARE @ID AS CHAR(5);

		SET @I = (NEXT VALUE FOR SEQEMP);
		
		SET @ID=DBO.GENID('E',@I);

		INSERT INTO EMP2
		VALUES(@ID, @N, @X);
		
		SELECT * FROM EMP2;

END;

ADDEMP2 'AJAY',27;