USE NORTHWND;

SELECT TITLE,COUNT(TITLE) FROM Employees
GROUP BY TITLE
HAVING TITLE='SALES MANAGER';

SELECT CUSTOMERID,COUNT(CUSTOMERID),SUM(FREIGHT) FROM ORDERS
WHERE EMPLOYEEID=1
GROUP BY CUSTOMERID
HAVING SUM(FREIGHT)>=100
ORDER BY SUM(FREIGHT) DESC;


SELECT CUSTOMERID, EMPLOYEEID,COUNT(ORDERID) AS'COUNT OF ORDERS',SUM(FREIGHT) AS 'SUM OF FREIGHT'FROM ORDERS
GROUP BY CUSTOMERID,EMPLOYEEID
HAVING SUM(FREIGHT)>=100
ORDER BY SUM(FREIGHT) DESC


WITH TEMP_TABLE AS (
SELECT CUSTOMERID, EMPLOYEEID,COUNT(ORDERID) AS'COUNT_OF_ORDERS',SUM(FREIGHT) AS 'SUM_OF_FREIGHT'FROM ORDERS
GROUP BY CUSTOMERID,EMPLOYEEID
HAVING SUM(FREIGHT)>=100
)
SELECT EMPLOYEEID, SUM(SUM_OF_FREIGHT) AS 'TOTAL_FREIGHT_BY_EMP' FROM TEMP_TABLE
GROUP BY EMPLOYEEID
ORDER BY EMPLOYEEID;


SELECT EMPLOYEEID, SUM(FREIGHT) AS 'TOTAL_FREIGHT_BY_EMP' FROM ORDERS
GROUP BY EMPLOYEEID
HAVING SUM(FREIGHT)>=100
ORDER BY EMPLOYEEID;

SELECT * FROM ORDERS;

