USE DEMO;

-- EXAMPLE OF THREE LAYERED SUQUERY SHOWN IN CLASS
SELECT COUNT(EID) AS 'DELHI TEAM MEMBERS GETTING 1lAC + SAL', AVG(SALARY) As 'DELHI EMP AVERAGE SALARY' FROM EMP_SAL
WHERE EID IN (SELECT EID FROM EMP WHERE CITY ='DEL'
					AND  EID IN ( SELECT EID FROM EMP_SAL WHERE SALARY >= 100000));

					--ASSIGNMENT

--A-1 : EID, NAME, CITY OF GURGAON EMPLOYEES
SELECT * FROM EMP;
SELECT EID,NAME,CITY FROM EMP
WHERE CITY='GGN';

--A-2 : EID, NAME , DOJ ,DEPT, DESI & SALARY OF ALL MANAGERS 
SELECT E.EID,E.NAME,ES.DOJ,ES.DEPT,ES.DESI,ES.SALARY 
FROM EMP E INNER JOIN EMP_SAL ES ON E.EID=ES.EID
WHERE ES.DESI='MGR';

--A-3: REDUCE THE SALARY OF ALL DELHI EMPLOYEES BY 10%. 
SELECT * FROM EMP_SAL
WHERE EID IN (SELECT EID FROM EMP WHERE CITY='DEL');

UPDATE EMP_SAL 
SET SALARY=SALARY*0.9
WHERE EID IN (SELECT EID FROM EMP WHERE CITY='DEL');

SELECT * FROM EMP_SAL
WHERE EID IN (SELECT EID FROM EMP WHERE CITY='DEL');

--A-4 : DISPLAY THE EID, NAME , CITY, DOJ ,DEPT, DESI & SALARY OF THE TEAM MEMBERS OF DAVID & RAMESH SAHRMA.

SELECT E.EID,E.NAME,E.CITY,ES.DOJ,ES.DEPT,ES.DESI,ES.SALARY 
FROM EMP E INNER JOIN EMP_SAL ES ON E.EID=ES.EID
WHERE ES.DEPT IN (SELECT DEPT FROM EMP_SAL WHERE EID IN (SELECT EID FROM EMP WHERE NAME LIKE '%SUMEDHA%' OR NAME LIKE '%RIDDHI%') );
 
--A-5: CREATE A TRAINING TABLE CONTAINING EID, NAME, DEPT. INSERT THE DETAILS OF OPS TEAM MEMBERS IN THE TRAINING TABLE. 
CREATE TABLE TRAINING(
EID CHAR(5),
NAME VARCHAR(30),
DEPT VARCHAR(10)
);

INSERT INTO TRAINING
SELECT E.EID, E.NAME,ES.DEPT 
FROM EMP E INNER JOIN EMP_SAL ES ON E.EID=ES.EID WHERE DEPT='OPS';

SELECT * FROM TRAINING;

--A-6: DETAILS OF DIRECTORS SHOULD BE DELETED FROM THE TRAINING TABLE. 
--WE WILL DELETE SARIKA FROM TRAINING TABLE
DELETE FROM TRAINING 
WHERE NAME IN (SELECT NAME FROM TRAINING WHERE NAME LIKE '%SARIKA%');

SELECT * FROM TRAINING;

--A-7: DISPLAY THE SALARY DETAILS OFF ALL EMPLOYES IF ANY OF THE TEAM MEMBER HAS SALARY MORE THAN 200000.


CREATE PROCEDURE SAL_DETAILS @X AS VARCHAR(10)
AS 
BEGIN 
	SELECT * FROM EMP_SAL
	WHERE EXISTS (SELECT * FROM EMP_SAL WHERE SALARY>=200000 AND DEPT=@X)
	AND DEPT=@X
END;

SAL_DETAILS 'IT';  --- TRY 'IT',

SELECT * FROM EMP_SAL;