USE DEMO;

SELECT * FROM EMP_SAL;


--A-1: DEPARTMENT WISE TEAM SIZE AND AVERAGE SALARY OF ALL EMPLOYEES.
SELECT DEPT,COUNT(DEPT) AS 'TEAM_SIZE',AVG(SALARY) AS 'AVG_SAL' FROM EMP_SAL
GROUP BY DEPT;

--A-2 : COUNT OF MANAGERS IN THE COMPANY. 
SELECT DESI, COUNT(DESI) AS 'COUNT_OF_MGR' FROM EMP_SAL
GROUP BY DESI
HAVING DESI='MGR';

SELECT COUNT(DESI) AS 'COUNT_OF_MGR' FROM EMP_SAL
WHERE DESI='MGR';


--A-3: MAXIMUM & MINIMUM SALARY OF AN ASSOCIATE
SELECT DESI,MAX(SALARY) AS 'MAX_SAL_OF_ASSO',MIN(SALARY) AS 'MIN_SAL_OF_ASSO' FROM EMP_SAL
GROUP BY DESI
HAVING DESI='ASSO';

SELECT MAX(SALARY) AS 'MAX_SAL_OF_ASSO',MIN(SALARY) AS 'MIN_SAL_OF_ASSO' FROM EMP_SAL
WHERE DESI='ASSO';

--A-4: DEPARTMENT WISE TEAM SIZE AND AVERAGE SALARY OF DELHI EMPLOYEES.
SELECT ES.DEPT,E.CITY,COUNT(ES.DEPT) AS 'TEAM_SIZE',AVG(ES.SALARY) AS 'AVG_SAL' 
FROM EMP E INNER JOIN EMP_SAL ES ON E.EID=ES.EID
GROUP BY ES.DEPT,E.CITY
HAVING E.CITY='DEL';

SELECT ES.DEPT,COUNT(ES.DEPT) AS 'TEAM_SIZE',AVG(ES.SALARY) AS 'AVG_SAL' 
FROM EMP E INNER JOIN EMP_SAL ES ON E.EID=ES.EID
WHERE E.CITY='DEL'
GROUP BY ES.DEPT;
 
--A-5: GENERATE OFFICIAL EMAIL OF THE EMPLOYEE TAKING 1ST CHARATCET OF FIRST NAME , 1ST CHARATCER OF LAST NAME , 
--LAST 3 DIGITS OF EID, FOLLED BY ‘RCG.COM’. EMAIL SHOULD BE IN A UPPER CASE. 

SELECT * FROM EMP
--DATA CHANGES FOR THIS TO SOLVE
UPDATE EMP SET NAME='SUMEDHA SINHA' WHERE EID='E0002';
UPDATE EMP SET NAME='KALPANA DHINGRA' WHERE EID='E0003';
UPDATE EMP SET NAME='DATTATREY SHINDE' WHERE EID='E0004';
UPDATE EMP SET NAME='DAKSHITA MAHAJAN' WHERE EID='E0005';
UPDATE EMP SET NAME='RIDDHI TYAGI' WHERE EID='E0006';
UPDATE EMP SET NAME='BABU GANDHI' WHERE EID='E0007';
UPDATE EMP SET NAME='JAYANT SANKHE' WHERE EID='E0008';
UPDATE EMP SET NAME='SARIKA MEHTA' WHERE EID='E0009';
UPDATE EMP SET NAME='TARUNKUMAR GUPTA' WHERE EID='E0010';

WITH T_NAME AS   
(SELECT EID,NAME, LEFT(NAME,1) AS 'F',SUBSTRING(NAME,CHARINDEX(' ',NAME)+1,1) AS 'S' , RIGHT(EID,3) AS 'T' FROM EMP)
SELECT EID,NAME,UPPER(CONCAT(F,S,T,'@RCG.COM')) AS 'NEW_EMAIL'FROM T_NAME;

SELECT EID,NAME,UPPER(CONCAT(LEFT(NAME,1),SUBSTRING(NAME,CHARINDEX(' ',NAME)+1,1), RIGHT(EID,3),'@RCG.COM')) AS 'NEW_EMAIL' 
FROM EMP;

--A-6: NAME,CITY , PHNO & EMAIL OF THE EMPLOYEES WHOSE AGE >=40. 
SELECT * FROM EMP

SELECT NAME,CITY,PHONE,EMAIL,DATEDIFF(YY,DOB,GETDATE()) AS 'AGE' FROM EMP
WHERE DATEDIFF(YY,DOB,GETDATE())>=30;

--A-7 EID, NAME DOJ OF EMPLOYEES WHO HAVE COMPLETED 5 YEARS IN THE COMPANY 
SELECT E.EID, E.NAME,ES.DOJ 
FROM EMP E INNER JOIN EMP_SAL ES ON E.EID=ES.EID 
WHERE DATEDIFF(YY,DOJ,GETDATE())>=5;

--A-8: DETAILS OF THE MANAGERS HAVING BIRTHDAY IN THE CURRENT MONTH 

--LETS CHANGE DOB OF 3 EMPLOYEES OUT OF WHICH 2 ARE MANAGERS HAVING MONTH OF CURRENT MONTHS
SELECT * FROM EMP;
SELECT * FROM EMP_SAL;

--BELOW TWO ARE MGR
UPDATE EMP SET DOB='1992-11-01' WHERE EID='E0005';
UPDATE EMP SET DOB='1998-11-05' WHERE EID='E0006';
--BELOW 1 EMP IS NON-MGR. IT IS ASSO
UPDATE EMP SET DOB='1982-11-18' WHERE EID='E0008';

SELECT E.EID,E.NAME,E.CITY,ES.DESI
FROM EMP E INNER JOIN EMP_SAL ES ON E.EID=ES.EID
WHERE MONTH(E.DOB)=MONTH(GETDATE()) AND ES.DESI='MGR';

--A-9 : EID, DEPT , DESI , SALARY OF THE EMPLOYEE WHO IS GETTING THE MAXIMUM SALARY 
SELECT TOP 1 * FROM EMP_SAL
ORDER BY SALARY DESC;

--A-10 : EID, NAME OF EMPLOYEE WHO HAS LONGEST NAME\

SELECT TOP 1 EID,NAME,LEN(NAME) FROM EMP 
ORDER BY LEN(NAME) DESC;

--FOLLOWING QUERY WILL GIVE ALL EMP WITH MAX LEN
WITH T AS
(
SELECT *,
   DENSE_RANK() OVER (ORDER BY LEN(NAME) Desc) AS Rnk
FROM Emp
)
SELECT EID,NAME,LEN(NAME) AS 'LEN_OF_NAME'
FROM T
WHERE Rnk=1;

--- ANOTHER OPTION USING VIEW
CREATE VIEW LEN_NAME AS
(
SELECT *,LEN(NAME) AS LEN_OF_NAME,DENSE_RANK() OVER (ORDER BY LEN(NAME) DESC) AS RNK FROM EMP
);

SELECT EID,NAME,LEN_OF_NAME FROM LEN_NAME WHERE RNK=1;

--DROP VIEW LEN_NAME;