--Time to Think!!

--Create a View for the below queries:

--From the employee table, we need to see the total salary as “TOTAL COST” for 
--each department arranged in the descending order of total salary .
USE DEMO;

CREATE VIEW V_EMP_SAL AS  
(SELECT DEPT, SUM(SALARY) AS 'TOTAL_COST' FROM EMP_SAL
GROUP BY DEPT);

SELECT * FROM V_EMP_SAL 
ORDER BY TOTAL_COST DESC;

--Also just show only those departments where “TOTAL COST” is greater than 50000.
SELECT * FROM V_EMP_SAL
WHERE TOTAL_COST>180000;


--ASSIGNMENT – 6 


--1 ) CREATE A VIEW EMP_SAL_DETAILS TO GET EID NAME DOJ DEPT DESI SALARY AS BASIC. 
--ALSO CALCULATE HRA (15% OF BASIC), PF (9% OF BASIC), NET(BASIC+HRA+PF), GROSS(NET-PF). 
USE DEMO;

SELECT * FROM EMP;
SELECT * FROM EMP_SAL;


CREATE VIEW  EMP_SAL_DETAILS AS
(SELECT E.EID, E.NAME, ES.DOJ,ES.DEPT,ES.SALARY AS 'BASIC', ES.SALARY*0.15 AS 'HRA', ES.SALARY*0.09 AS 'PF',
ES.SALARY+ES.SALARY*0.15+ES.SALARY*0.09 AS 'NET', ES.SALARY+ES.SALARY*0.15 AS 'GROSS'
FROM EMP E 
INNER JOIN EMP_SAL ES ON E.EID=ES.EID);

SELECT * FROM EMP_SAL_DETAILS;


--2) CREATE A VIEW TO DISPLAY EID,NAME, DOJ, DESI, DEPT OF ALL THE MANAGERS JOINED IN 2009 OR 2019. 

SELECT * FROM EMP_SAL;

CREATE VIEW MANGERS_JOINED_IN_09_19 AS
(SELECT E.EID,E.NAME,ES.DOJ,ES.DESI,ES.DEPT 
FROM EMP E
INNER JOIN EMP_SAL ES 
ON E.EID=ES.EID
WHERE ES.DESI='MGR' AND YEAR(ES.DOJ) IN ('2019','2009')
);

SELECT * FROM MANGERS_JOINED_IN_09_19;


--3) IN THE INVENTORY STRUCTURE GENERATE A VIEW BILL. 
--IT SHOULD DISPLAY OID,ODATE,CNAME,ADDRESS,PHONE,PDESC, PRICE, OQTY, AMOUNT
USE INVENTORY;

CREATE VIEW BILL AS
(SELECT O.OID,O.ODATE,C.CNAME,C.ADDRESS,C.PHONE,P.PDESC,P.PRICE,O.OQTY, P.PRICE*O.OQTY AS 'TOTAL_BILL_AMOUNT'
FROM ORDERS O 
INNER JOIN CUST C ON O.CID=C.CID
INNER JOIN PRODUCT P ON P.PID=O.PID
);

SELECT * FROM BILL;
