--IN THE EMP TABLE DISPLAY : 


 USE DEMO;
--1 ) EID NAME CITY DOJ DEPT DESI SALARY OF THE DELHI EMPLOYEES 
SELECT * FROM EMP;
SELECT * FROM EMP_SAL;

-- LETS ADD FEW RECORDS TO EMP TABLE WHICH ARE NOT IN EMP_SAL
INSERT INTO EMP
VALUES ('E0011','NAYRA ARORA','SECTOR 11','NOIDA','05-JAN-1997','4568745621','NY.ARO@YAHOO.COM');
INSERT INTO EMP
VALUES ('E0012','SIMRAN MISHRA','AMRDHAM','FBD','05-SEP-1995','4568746621','SIMRAN@YAHOO.COM');

--INSERT INTO EMP_SAL
--VALUES ('E0013','OPS','ASSO','22-DEC-2015',80000);

--INSERT INTO EMP_SAL
--VALUES ('E0014','IT','ASSO','18-FEB-2017',70000);

SELECT E.EID, E.NAME,E.CITY,ES.DOJ,ES.DEPT,ES.SALARY
FROM EMP E 
INNER JOIN EMP_SAL ES
ON E.EID=ES.EID
WHERE E.CITY='DEL';

--2 ) DETAILS OF ALL THE EMPLOYEES WHOSE SALARY DETAILS ARE NOT AVAILABLE.

-- THIS JUST CHECKS WHETHER THE SALARY IS AVAILABE OR NOT.
SELECT * 
FROM EMP E
LEFT JOIN EMP_SAL ES
ON E.EID=ES.EID
WHERE ES.SALARY IS NULL;

-- THIS WILL CHECK WHETHER THIS EMPLOYEE IS IN EMP_SAL DATA OR NOT
SELECT * 
FROM EMP E
LEFT JOIN EMP_SAL ES
ON E.EID=ES.EID
WHERE NOT E.EID IN (SELECT EID FROM EMP_SAL);


